// src/client-react/src/App.js
import './App.css';
import React, { useEffect, useCallback } from 'react'
import { makeStyles } from '@material-ui/core/styles';
import { AppBar, Toolbar, Typography, LinearProgress } from '@material-ui/core'
import { teal, orange } from '@material-ui/core/colors';
import RouteConfig from './RouteConfig';
import AlertBox from './views/content/AlertBox'
import VoteDialog from './views/dialogs/VoteDialog'
import { useSelector, useDispatch } from 'react-redux'
import { selectIsFetching } from './store/globalSlice'
import signalRService from './services/signalRService'
import { selectQuestions, selectAnswers, getAnswers, getQuestions } from './store/resourceSlice'
import { selectStats, getStats, vote } from './store/surveySlice'
import { createMuiTheme, ThemeProvider } from '@material-ui/core';

const useStyles = makeStyles((theme) => ({
  appBar: {
    position: 'relative',
    color: teal[50],
  },
  title: {
    flexGrow: 1,
  },
  layout: {
    width: 'auto',
    padding: theme.spacing(4),
  },
  voteButton: {
    color: teal[50],
  },
}));

const theme = createMuiTheme({
  palette: {
    primary: {
      main: teal[800],
    },
    secondary: {
      main: orange[600],
    }
  }
})

function App() {
  const classes = useStyles();
  const isFetching = useSelector(selectIsFetching)
  const questions = useSelector(selectQuestions);
  const answers = useSelector(selectAnswers);
  const stats = useSelector(selectStats);
  const dispatch = useDispatch();

  const onSaveVote = useCallback((response) => {
    dispatch(vote(response));
  }, []);

  useEffect(() => {
    signalRService.initialize();

    if(questions.length == 0) {
      dispatch(getQuestions());
    }

    if(answers.length == 0) {
      dispatch(getAnswers());
    }

    if(stats.length == 0) {
      dispatch(getStats());
    }

  }, []);

  return (
    <div>
      <ThemeProvider theme={theme}>
        <AppBar className={classes.appBar} color="primary">
          <Toolbar>
            <Typography variant="h6" className={classes.title}>
              Favorites Survey
            </Typography>
            <VoteDialog className={classes.voteButton} onSave={onSaveVote} />
          </Toolbar>
        </AppBar>
        { isFetching ? <LinearProgress /> : null }
        <main className={classes.layout}>
          <RouteConfig />
          <AlertBox />
        </main>
      </ThemeProvider>
    </div>
  );
}

export default App;

// src/client-vue/src/App.vue
<template>
  <v-app>
    <v-app-bar app
              color="#00695c"
              fixed
              dark>
      <div class="d-flex align-center">
        <h2 class="ml-5">Favorites Survey</h2>
      </div>

      <v-spacer></v-spacer>
      <VoteDialog @on-save="onSaveVote" />
    </v-app-bar>

    <v-main>
      <v-progress-linear indeterminate color="cyan" v-show="isFetching" />
      <v-container>
        <router-view />
        <AlertBox />
      </v-container>
    </v-main>
  </v-app>
</template>

<script>

import AlertBox from '@/views/content/AlertBox'
import VoteDialog from '@/views/dialogs/VoteDialog'
import signalRService from '@/services/signalRService'
import { mapState } from 'vuex'
import modules from '@/store/types/moduleTypes'
import actions from '@/store/types/actionTypes'

export default {
  name: 'App',

  components: {
    AlertBox,
    VoteDialog
  },

  data: () => ({
    //
  }),

  computed: {
    ...mapState(['isFetching']),
    ...mapState(modules.Resource, [
      'questions',
      'answers'
    ]),
    ...mapState(modules.Survey, [
      'stats'
    ]),
  },

  methods: {
    onSaveVote($event) {
      this.$store.dispatch(`${modules.Survey}/${actions.Vote}`, $event.vote);
    },
  },

  created() {
    signalRService.initialize();

    if(this.questions.length == 0) {
      this.$store.dispatch(`${modules.Resource}/${actions.GetQuestions}`);
    }

    if(this.answers.length == 0) {
      this.$store.dispatch(`${modules.Resource}/${actions.GetAnswers}`);
    }

    if(this.stats.length == 0) {
      this.$store.dispatch(`${modules.Survey}/${actions.GetStats}`);
    }
  },
};
</script>

<style>
html {
  margin: 0;
  padding: 0;
  overflow-y: auto;
}
</style>
